blacktechies/apps/messaging/models.py
import datetime
import time
from blacktechies.database import db


class Message(db.Model):
    """Model representing a message from one user to one or more
    users. The `is_read` flag only makes sense when the conversation
    has two people."""

    STATUS_ACTIVE = 0
    STATUS_DELETED = 1

    __tablename__ = 'messages'
    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversations.id'), nullable=False, index=True)
    from_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    status = db.Column(db.Integer, nullable=False, default=STATUS_ACTIVE)
    body = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)
    is_read = db.Column(db.Boolean, nullable=False, default=False)
    # Relationship columns
    sender = db.relationship('User', uselist=False, foreign_keys=[from_user_id])
    conversation = db.relationship('Conversation', uselist=False, foreign_keys=[conversation_id])

    def __str__(self):
        return self.body

    def delete(self):
        self.status = self.STATUS_DELETED

    @classmethod
    def from_string(cls, message, subject=None, **kwargs):
        msg_args = {
            'body': message,
            'status': cls.STATUS_ACTIVE,
            'timestamp': datetime.datetime.now(),
            'is_read': False,
        }
        msg_args.update(kwargs)
        return cls(**msg_args)

    @classmethod
    def most_recent(cls, conversations, limit=None):
        if limit is None:
            limit = 1
        selects = []
        seen_ids = set()
        # These are dealing with the SQLAlchemy metadata objects and not
        # instances of the class.
        message = db.metadata.tables.get(cls.__tablename__)
        c_meta = db.metadata.tables.get(Conversation.__tablename__)
        for conversation in conversations:
            if conversation.id in seen_ids:
                continue
            seen_ids.add(conversation.id)
            selects.append(
                db.select([message]).where(
                    message.c.conversation_id == c_meta.c.id).limit(limit)
            )
        result = db.engine.execute(db.union_all(*selects))
        if not result or not result.returns_rows:
            raise RuntimeError("Query for most recent messages did not return a valid result")
        message_map = {}
        for row in result.fetchall():
            if row.conversation_id not in message_map:
                message_map[row.conversation_id] = []
            message_map[row.conversation_id].append(row)
        return message_map

    @classmethod
    def for_conversation(cls, conversation, before_id=None, limit=None):
        query = cls.query.filter(cls.conversation_id == conversation.id)
        query.filter(cls.status == cls.STATUS_ACTIVE)
        if before_id:
            query.filter(Message.id < before_id)
        query.order_by(Message.id.desc()).limit(limit)
        return query.all()


class Conversation(db.Model):
    STATUS_ACTIVE = 0
    STATUS_DELETED = 1

    __tablename__ = 'conversations'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Integer, nullable=False, default=STATUS_ACTIVE)
    last_updated = db.Column(db.Integer, nullable=False, default=int(time.time()))
    subject = db.Column(db.Text, nullable=False, default='')
    messages = db.relationship('Message')
    users = db.relationship('User', backref="conversations",
                            secondary="conversations_users")


    def add_user(self, user):
        conv_user = ConversationUser(status=ConversationUser.STATUS_ACTIVE,
                                     joined=datetime.datetime.now())
        conv_user.user = user
        self.users.append(conv_user)

    def has_user(self, user, active_only=True):
        for conv_user in self.users:
            if conv_user.id == user.id:
                if not active_only or (active_only and conv_user.is_active()):
                    return True
        return False

    def remove_user(self, user):
        for conv_user in self.users:
            if conv_user.user_id == user.id:
                conv_user.status = ConversationUser.STATUS_PARTED

    def add_message(self, message):
        self.messages.append(message)

    def new_message(self, message, user):
        m = Message.new_message(message, user=user, conversation=self)
        self.add_message(m)
        return m

    def other_users(self, user):
        others = []
        for other in self.users:
            if other.id != user.id:
                others.append(other)
        return others

class ConversationUser(db.Model):
    """ All of the users who can participate in a conversation.

    All conversations are able to be shared between multiple users.
    """
    STATUS_ACTIVE = 0
    STATUS_PARTED = 1

    __tablename__ = 'conversations_users'
    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey('conversations.id'), index=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    joined = db.Column(db.DateTime, nullable=False, default=datetime.datetime.now())
    # When a user has parted a conversation, they no longer should see messages
    status = db.Column(db.Integer, nullable=False, default=STATUS_ACTIVE)
    __table_args__ = (db.UniqueConstraint('user_id', 'conversation_id', name="uix_conversation_users"),)
    # Relationship attributes
    user = db.relationship("User")

    @classmethod
    def exists(cls, user_id, conversation_id):
        return db.exists(ConversationUser.query.filter(db.and_(
            cls.user_id == user_id, cls.conversation_id == conversation_id)))

blacktechies/apps/messaging/forms.py
from wtforms import validators
from wtforms.fields import StringField, TextAreaField, HiddenField

from blacktechies.utils.validation import FormTimestamp
from blacktechies.utils.form import Form, generate_ts


class NewMessageForm(Form):
    """ A class for sending a message to another user """
    subject = StringField('Subject', validators=[
        validators.optional(),
        validators.length(max=200, message="The subject is too long")])
    body = TextAreaField('Your Message', validators=[
        validators.required(),
        validators.length(max=5*1024, message="Your message is too long")])
    timestamp = HiddenField(default=generate_ts(), validators=[
        validators.required(),
        FormTimestamp(days=1, message="This form has expired, please reload the page.")])
    to_usernames = TextAreaField(validators=[validators.required(message="You have to send this message to someone")])

    def filtered_usernames(self, usernames_str=None):
        if usernames_str is None:
            usernames_str = self.to_usernames.data or ''
        names = map(usernames_str.strip, usernames_str.split(','))
        return names


class ReplyForm(Form):
    body = TextAreaField('Your Message', validators=[
        validators.required(message="You must include a message"),
        validators.length(max=5*1024, message="Your message is too long")])
    timestamp = HiddenField(default=generate_ts(), validators=[
        validators.required(),
        FormTimestamp(days=1, message="This form has expired, please reload the page.")])
    conversation_id = HiddenField(validators=[validators.required(message="Replies to a thread must have a conversation_id")])

blacktechies/apps/messaging/views.py
import datetime

from flask import Blueprint, render_template, request, current_app, redirect, abort, url_for
from flask_login import current_user, login_required

from blacktechies.database import db
from blacktechies.apps.user.models import User
from blacktechies.apps.messaging.forms import NewMessageForm, ReplyForm
from blacktechies.apps.messaging.models import Message, Conversation, ConversationUser

mod = Blueprint('messaging', __name__, url_prefix='/messages', template_folder="templates")


@mod.route("/")
@login_required
def index():
    before_timestamp = request.args.get('before', 0)

    conversations = Conversation.query.from_statement(db.text(
        """
        SELECT c.* FROM conversations c
        INNER JOIN conversations_users cu
        ON c.id = cu.conversation_id
        WHERE cu.user_id = :userid
        AND c.last_updated > :before
        LIMIT 25
        """)).params(userid=current_user.id, before=before_timestamp).all()
    messages = Message.most_recent(conversations)
    return render_template('messaging/index.html',
                           conversations=conversations,
                           messages=messages)


@mod.route("/new", methods=['GET', 'POST'])
@login_required
def new_message():
    form = NewMessageForm()
    try:
        if form.validate_on_submit():
            message = Message.from_string(request.form['body'])
            message.sender = current_user

        conversation = Conversation()
        conversation.subject = request.form.get('subject')
        to_usernames = form.filtered_usernames(request.form['to_usernames'])
        if not to_usernames:
            raise ValueError("No valid recipients found")

        # Find all users with the usernames
        users = User.query.filter(User.username.in_(to_usernames)).all()
        if len(users) != len(set(to_usernames)):
            raise ValueError("Not all recipients were found")

        conversation.users.append(current_user)
        for user in users:
            if user.id != current_user.id:
                conversation.users.append(user)

        conversation.messages.append(message)
        db.session.add(conversation)
        if db.session.commit():
            return redirect(url_for('messaging.conversation_index',
                                    conversation_id=conversation.id), 303)
    except:
        raise
    form.timestamp.data = form.current_timestamp()
    return render_template('messaging/new.html',
                           conversation=conversation,
                           form=form)


@mod.route("/<int:conversation_id>/reply", methods=['GET', 'POST'])
@login_required
def new_reply(conversation_id):
    form = ReplyForm()
    conversation = Conversation.query.get(conversation_id)
    if not conversation or not conversation.has_user(current_user):
        return abort(404)

    try:
        if (form.validate_on_submit() and
                int(request.form['conversation_id']) == conversation_id):
            message = Message.from_string(request.form['body'])
            message.sender = current_user
            conversation.messages.append(message)
            db.session.add(conversation)
            db.session.commit()
            return redirect(url_for('messaging.conversation_index',
                                    conversation_id=conversation.id), 303)
    except:
        raise
    form.timestamp.data = form.current_timestamp()
    return conversation_index(conversation_id, form)

@mod.route("/<int:conversation_id>")
@login_required
def conversation_index(conversation_id, form=None):
    before = request.args.get('before', 0)
    limit = request.args.get('limit', 25)
    try:
        limit = int(limit)
    except:
        limit = 0
    if limit < 1 or limit > 50:
        limit = 25

    c = Conversation.query.filter_by(id=conversation_id).first_or_404()
    if not c.has_user(current_user):
        return abort(404)
    if form is None:
        form = ReplyForm()

    form.conversation_id.data = conversation_id
    messages = Message.for_conversation(c, limit=limit, before_id=before)
    return render_template('messaging/conversation.html', conversation=c,
                           messages=messages, form=form)

blacktechies/apps/messaging/templates/messaging/_reply_form.html
{% from 'helpers/_wtformhelpers.html' import render_field %}

<form method="POST"
      action="{{ url_for('messaging.new_reply', conversation_id=conversation.id) }}">

      {{ form.hidden_tag() }}
      {{ render_field(form.body) }}
      <button type="submit" class="btn btn-primary">Reply</button>
</form>

blacktechies/apps/messaging/templates/messaging/base.html
{% extends "layouts/base.html" %}

blacktechies/apps/messaging/templates/messaging/conversation.html
{% extends "messaging/base.html" %}

{% block title %}
  Subject: {{ conversation.subject|default('(none)', true) }}
{% endblock %}

{% block main_content %}
  <h3>{{ conversation.subject}}</h3>
  <ul class="list-unstyled">
    {% for message in messages %}
      <li>
        <div class="panel panel-default">
          <div class="panel-heading">From: {{ message.sender.username }}
            <div class="pull-right">Sent: {{ message.timestamp }}</div>
          </div>
          <div class="panel-body">{{ message.body }}</div>
        </div>

      </li>
    {% else %}
      <li>No messages found. Maybe they were all deleted?</li>
    {% endfor %}
  </ul>
  {% if form %}
    {% include "messaging/_reply_form.html" %}
  {% endif %}
{% endblock %}

blacktechies/apps/messaging/templates/messaging/index.html
{% extends "messaging/base.html" %}

{% block title %}Inbox{% endblock %}

{% block main_content %}
  <ul>
    {% for conversation in conversations %}
      <li>
        {% set other_users = conversation.other_users(g.user) %}
        {% set ct = other_users|length() %}
        {%- if ct == 0: -%}
          <div>This one is a secret. Shh!</div>
        {%- elif ct == 1: %}
          <div>Between you and {{ other_users[0].username }}</div>
        {%- else: -%}
          <div>Between you and {{ ct }} others</div>
        {%- endif -%}
        <div>
          <a href="{{ url_for('messaging.conversation_index', conversation_id=conversation.id) }}">
            {{ messages[conversation.id][0].body }}
          </a>
        </div>
      </li>
  {% endfor %}
  </ul>

{% endblock %}

blacktechies/apps/messaging/templates/messaging/new.html
{% extends "messaging/base.html" %}
{% from 'helpers/_wtformhelpers.html' import render_field %}

{% block title %}
  {% if is_conversation: %}
    Reply to Thread
  {% else: %}
    Create New Message
  {% endif %}
{% endblock %}

{% block main_content %}

  <form class="form" method="POST"
        {%- if is_conversation: -%}
          action="{{ url_for('messaging.new_reply', conversation_id=conversation_id) }}"
        {%- else: -%}
          action="{{ url_for('messaging.new_message') }}"
        {%- endif -%}
        >
        {{ form.hidden_tag() }}
        {{ render_field(form.to_usernames) }}
        {% if not is_conversation: %}
          {{ render_field(form.subject) }}
        {% endif %}
        {{ render_field(form.body) }}
        <button type="submit" class="btn btn-primary">Send</button>
  </form>
{% endblock %}